config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  devise_for :users
  resources :users
  get 'new_transaction', to: "users#new_transaction"
  get 'total_transaction', to: "users#total_transaction"
  post 'users/user_create', to: "users#user_create"
  post 'users/create_transaction', to: "users#create_transaction"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/salesforce_model.rb
module SalesforceModel
  extend ActiveSupport::Concern

  def hc_errors
    HerokuconnectTriggerLog.where(:record_id => self.id, :state => 'FAILED').order("id DESC").all
  end

  def hc_last_error
    errs = hc_errors()
    errs[0] ? errs[0].sf_message : nil
  end

  def set_sfid
    self.sfid = SecureRandom.hex(5) if self.sfid.nil?
  end

  included do
    unless Rails.env.production?
      before_save :set_sfid
    end

    if Rails.env.test?
      establish_connection ENV['HEROKUCONNECT_URL_TEST']
    else
      establish_connection ENV['HEROKUCONNECT_URL']
    end
  end
end

class HerokuconnectTriggerLog < ActiveRecord::Base
  include SalesforceModel
  self.table_name = ENV['HEROKUCONNECT_SCHEMA'] + '._trigger_log'

  def self.pending
    HerokuconnectTriggerLog.where(:state => 'NEW').count
  end
end

app/models/salesforce/contact.rb
class Salesforce::Contact < ApplicationRecord
  include SalesforceModel
  self.table_name =  ENV['HEROKUCONNECT_SCHEMA'] + '.contact'
end

app/models/salesforce/middle_man_transaction.rb
class Salesforce::MiddleManTransaction < ApplicationRecord
  include SalesforceModel
  self.table_name =  ENV['HEROKUCONNECT_SCHEMA'] + '.middlemantransaction__c'
end

app/models/salesforce/transaction_comment.rb
class Salesforce::TransactionComment < ApplicationRecord
  include SalesforceModel
  self.table_name =  ENV['HEROKUCONNECT_SCHEMA'] + '.transaction_comments__c'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :invitable

	def send_reset_password_instructions
	 	UserMailer.reset_password_instructions(self.email).deliver
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(resource)
	 total_transaction_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to root_path, :alert => "Access denied."
    end
  end

  def user_create

    User.invite!({:email => params[:sender_email]}) unless User.find_by_email(params[:sender_email]).present? && User.find_by_email(params[:sender_email]).invitation_accepted_at.present? 
    seller = Salesforce::Contact.find_or_initialize_by(email: params[:sender_email], lastname: "testing")
    if seller.new_record?
      seller.heroku_id__c = SecureRandom.hex(10)
    end
    seller.save

    User.invite!({:email => params[:buyer_email]}) unless User.find_by_email(params[:buyer_email]).present? && User.find_by_email(params[:buyer_email]).invitation_accepted_at.present?
    buyer = Salesforce::Contact.find_or_initialize_by(email: params[:buyer_email], lastname: "testing")
    if buyer.new_record?
      buyer.heroku_id__c = SecureRandom.hex(10)
    end
    buyer.save

    Salesforce::MiddleManTransaction.create(buyer_email__c: buyer.email, seller_email__c: seller.email, heroku_id__c: SecureRandom.hex(10))
    redirect_to root_path, :notice => "Begin Transaction successfully..!"
  end

  def total_transaction
    @buyes_records = Salesforce::MiddleManTransaction.where(buyer_email__c: current_user.email)
    @seller_records = Salesforce::MiddleManTransaction.where(seller_email__c: current_user.email)
  end

  def new_transaction
    @comments = Salesforce::TransactionComment.where(middlemantransactions__c: params[:id])
  end

  def create_transaction
    comment = Salesforce::TransactionComment.new(middlemantransactions__c: params[:middlemantransactions], comments__c: params[:comments__c])
    comment.save
    redirect_to new_transaction_path(:id => params[:middlemantransactions])
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li class="nav-item ">
    <a class="nav-link" href="/users/edit">Edit account <span class="sr-only">(current)</span></a>
  </li>
  <li class="divider-vertical"></li>
  <li class="nav-item ">
    <%= link_to 'Sign out', destroy_user_session_path, :method=>'delete', :class => "nav-link" %>
  </li>
  <li class="divider-vertical"></li>
<% else %>
  <li class="nav-item ">
    <a class="nav-link" href="/users/sign_in">SIGN IN <span class="sr-only">(current)</span></a>
  </li>
  <li class="divider-vertical"></li>
  <li class="nav-item ">
    <a class="nav-link" href="/users/sign_up">SIGN UP <span class="sr-only">(current)</span></a>
  </li>
  <li class="divider-vertical"></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar  navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="nav-item ">
          <a class="nav-link" href="/">HOME <span class="sr-only">(current)</span></a>
        </li>
        <li class="divider-vertical"></li>
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li class="nav-item ">
	<a class="nav-link" href="/pages/about">ABOUT <span class="sr-only">(current)</span></a>
</li>
<li class="divider-vertical"></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Middle Man" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Middle Man" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/new_transaction.html.erb
<div class="row">
   <div class="col-sm-4">
   </div>
   <div class="col-sm-4">
     <%= image_tag('logo.png',:class => "img-responsive") %>
   </div>
   <div class="col-sm-4">
   </div>
</div>

<div class="col-sm-12 margin-top-50">
  <div class="timeline">
    <% @comments.each_with_index do |comment, index| %>
      <% direction = ((index + 1) % 2) === 1 ? 'left' : 'right' %>
      <div class="container <%=direction%>">
        <div class="content">
          <div class="row" >
            <div class="col-sm-3">
                <i class="fa fa-user"></i>
            </div>
            <div class="card text-left col-sm-8 buy">
              <div class="card-header">
                <%= comment.name || 'BUYER'%>
              </div>
              <div class="card-body">
                <p class="card-text"> <%= comment.comments__c%></p>
              </div>
            </div>    
          </div>
        </div>
      </div>
    <%end%>
  </div>  
</div>
<div class="row">
  <%= form_tag users_create_transaction_path, :method => :post do %>
   <div class="col-sm-4">
   </div>
   <div class="col-sm-4">
   </div>
    <div class="col-sm-4">
    </div>
    <div class="col-sm-8 comment-form">
      <div class="col-sm-12">
        <textarea cols="25" id="body" name="comments__c" required="true" class="form-control" placeholder="" rows="4"></textarea>
        <input type="hidden" name="middlemantransactions" value=<%= params[:id]%> />
      </div>
      <div class="col-sm-12">
        <button type="submit" class="btn float-right comment-submit">Post</button>
      </div>
    </div>
  <% end %>
</div>
<style>
* {
    box-sizing: border-box;
}

body {
/*    background-color: #474e5d;*/
    font-family: Helvetica, sans-serif;
}

/* The actual timeline (the vertical ruler) */
.timeline {
    position: relative;
    max-width: 1200px;
    margin: 0 auto;
}

/* The actual timeline (the vertical ruler) */
.timeline::after {
    content: '';
    position: absolute;
    width: 6px;
    background-color: #ccc;
    top: 0;
    bottom: 0;
    left: 50%;
    margin-left: -3px;
}

/* Container around content */
.timeline .container {
    padding: 10px 40px;
    position: relative;
    background-color: inherit;
    width: 50%;
    margin-left: initial;
}

/* The circles on the timeline */
.timeline .container::after {
    content: '';
    position: absolute;
    width: 25px;
    height: 25px;
    right: -17px;
    background-color: white;
    border: 4px solid #FF9F55;
    top: 15px;
    border-radius: 50%;
    z-index: 1;
}

/* Place the container to the left */
.left {
    left: 0;
}

/* Place the container to the right */
.right {
    left: 50%;
}

/* Add arrows to the left container (pointing right) */
.left::before {
    content: " ";
    height: 0;
    position: absolute;
    top: 22px;
    width: 0;
    z-index: 1;
    right: 30px;
    border: medium solid white;
    border-width: 10px 0 10px 10px;
    border-color: transparent transparent transparent white;
}

/* Add arrows to the right container (pointing left) */
.right::before {
    content: " ";
    height: 0;
    position: absolute;
    top: 22px;
    width: 0;
    z-index: 1;
    left: 30px;
    border: medium solid white;
    border-width: 10px 10px 10px 0;
    border-color: transparent white transparent transparent;
}

/* Fix the circle for containers on the right side */
.right::after {
    left: -16px;
}

/* The actual content */
.content {
    padding: 20px 30px;
    background-color: #ccc;
    position: relative;
    border-radius: 6px;
}

/* Media queries - Responsive timeline on screens less than 600px wide */
@media screen and (max-width: 600px) {
  /* Place the timelime to the left */
  .timeline::after {
    left: 31px;
  }
  
  /* Full-width containers */
.timeline  .container {
    width: 100%;
    padding-left: 70px;
    padding-right: 25px;
  }
  
  /* Make sure that all arrows are pointing leftwards */
.timeline .container::before {
    left: 60px;
    border: medium solid white;
    border-width: 10px 10px 10px 0;
    border-color: transparent white transparent transparent;
  }

  /* Make sure all circles are at the same spot */
  .left::after, .right::after {
    left: 15px;
  }
  
  /* Make all right containers behave like the left ones */
  .right {
    left: 0%;
  }
}
</style>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/users/total_transaction.html.erb
<div class="container">
	<header class=" text-white text-center ">
		<div class="row">
		   <div class="col-sm-4">
		   </div>
		   <div class="col-sm-4">
		     <%= image_tag('logo.png',:class => "img-responsive") %>
		   </div>
		    <div class="col-sm-4">
		    </div>
		</div>
	</header>
	<h2>Buyer Transactions</h2>
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">sfid</th>
        <th scope="col">Status</th>
      </tr>
    </thead>
    <tbody>
      <% @buyes_records.each do |buyer| %>
        <tr>
          <th scope="row"><%= link_to buyer.id, new_transaction_path(:id => buyer.sfid) %></th>
          <td><%= buyer.name  %></td>
          <td><%= buyer.sfid  %></td>
          <td>Pending..</td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <h2>Seller Transactions</h2>
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">sfid</th>
        <th scope="col">Status</th>
      </tr>
    </thead>
    <tbody>
      <% @seller_records.each do |seller| %>
        <tr>
          <th scope="row"><%= seller.id%></th>
          <td><%= seller.name  %></td>
          <td><%= seller.sfid  %></td>
          <td>Pending..</td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/visitors/index.html.erb
    <div class="container"> 
    <header class=" text-white text-center ">
    <div class="row">
      <%= form_tag users_user_create_path, :method => :post do %>
       <div class="col-sm-4">
        <input type="email" name="sender_email" required="true" class="btn btn-outline-light" placeholder="SELLERS E-MAIL">
       </div>
       <div class="col-sm-4">
         <%= image_tag('logo.png',:class => "img-responsive") %>
          <button type="submit" class="btn btn-outline-light color-g">BEGIN TRANSCTION</button>
       </div>
        <div class="col-sm-4">
        <input type="email" name="buyer_email" required="true" class="btn btn-outline-light" placeholder="BUYERS E-MAIL">
        </div>
      <% end %>
    </div>
    </header>
<hr>
<div class="row mid">
<div class="col-sm-6 left-line">
<h3>Buy or sell online without the fear of being cheated.</h3>
<p>MiddleMan.co specializes in managing transactions of virtual items.
   Ourcompany will make sure that you buy/sell safely without the fear or 
   chargebacks, and that the item you purchased is as described. </p>
   <%= image_tag('assure.jpg',width: "65%", :class => "img-responsive") %>
</div>
<div class="col-sm-6 padding-left">
  <h6><b>Complete protection for all transactIons</b></h6>
<span>It's fast, easy, and secure. </span>
<ol>
  <li> Start a transaction</li>
  <li>Set terms </li>
  <li>Buyer sends MiddleMan the payment</li>
  <li>MiddleMan secures the property</li>
  <li>Upload a mutual agreement, MiddleMan 
    releases the property and the payment to the rightful owners</li>

</ol>
</div>
</div>
<hr>
<h3 class="text-center">If it's virtual in nature, you can buy it or sell it safely using MiddleMan</h3>
</div>
    <section class="features-icons bg-light text-center">
      <div class="container-90">
        <div class="row ">
          <div class="col-lg-6 text-center bg">
            <div class="">
 
              <h5>We offer an easy to use, chat like transactions!</h5>
              <p class="lead mb-0">We offer an easy to use, chat like transactions!</p>
              <div class="row mid-check-row">
                <div class="col-sm-6 text-left  ">
                  <div class="padding-checkbox">
                    <div class="form-check">
                        <input class="form-check-input" checked type="checkbox" value="" id="defaultCheck1">
                        <label class="form-check-label" for="defaultCheck1">
                          Gaming
                        </label>
                      </div>
                      <div class="form-check">
                          <input class="form-check-input" checked type="checkbox" value="" id="defaultCheck1">
                          <label class="form-check-label" for="defaultCheck1">
                            Social
                          </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" checked type="checkbox" value="" id="defaultCheck1">
                            <label class="form-check-label" for="defaultCheck1">
                              Websites
                            </label>
                          </div>
                          <div class="form-check">
                              <input class="form-check-input" checked type="checkbox" value="" id="defaultCheck1">
                              <label class="form-check-label" for="defaultCheck1">
                                Data
                              </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input"  checked type="checkbox" value="" id="defaultCheck1">
                                <label class="form-check-label" for="defaultCheck1">
                                  Software
                                </label>
                              </div>     </div>
                </div>
                <div class="col-sm-6 text-left">
                    <div class="form-check">
                        <input class="form-check-input" checked type="checkbox" value="" id="defaultCheck1">
                        <label class="form-check-label" for="defaultCheck1">
                          Services
                        </label>
                      </div>
                      <div class="form-check">
                          <input class="form-check-input" checked type="checkbox" value="" id="defaultCheck1">
                          <label class="form-check-label" for="defaultCheck1">
                            Influence
                          </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" checked type="checkbox" value="" id="defaultCheck1">
                            <label class="form-check-label" for="defaultCheck1">
                              Domains
                            </label>
                          </div>
                          <div class="form-check">
                              <input class="form-check-input" checked type="checkbox" value="" id="defaultCheck1">
                              <label class="form-check-label" for="defaultCheck1">
                                Custom Scripts
                              </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" checked  type="checkbox" value="" id="defaultCheck1">
                                <label class="form-check-label" for="defaultCheck1">
                                  Odd requests
                                </label>
                              </div>
                </div>

              </div>
              <h5>We make transfers of virtual items easy and hassle-free! </h5>
            </div>
          </div>
          <div class="col-lg-6">
              <div class="row">
                  <div class="col-sm-2">
                      <i class="fa fa-user"></i>


                  </div>
                <div class="card text-left col-sm-8 buy">
                    <div class="card-header">
                      BUYER
                    </div>
                    <div class="card-body">
                      
                      <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                    
                    </div>
                  </div>
                  
                  </div>
                  <div class="row sell">
                      <div class="col-sm-2">
                          <i class="fa fa-user"></i>


                      </div>
            <div class="card text-left col-sm-8 ">
                <div class="card-header">
                  SELLER
                </div>
                <div class="card-body">
              
                  <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                 
                </div>
              </div>
            </div>
              <div class="row logo-box">
                  <div class="col-sm-2">
                      <%= image_tag('mm.png', :class => "img-responsive") %>
                  </div>
                  <div class="card text-left col-sm-7 ">
                      <div class="card-header green">
                        MiddleMan
                      </div>
                      <div class="card-body">
                      <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                        
                      </div>
                    </div>
              </div>
              
          </div>
        
        </div>
      </div>
    </section>